import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                {children}
                <footer style={{ textAlign: "center", padding: "2rem 0" }}>
                    <small>
                        Made by{" "}
                        <a href="https://www.dehlimusikk.no" target="_blank" rel="noopener noreferrer">
                            Benjamin Dehli / Dehli Musikk
                        </a>
                    </small>
                </footer>
            </body>
        </html>
    );
}
